[package]
name = "replacer"
version = "0.1.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
encoding_rs = "0.8.35"
indicatif = "0.18.2"
